permissions:
  contents: write

name: Auto Blogger (diagnostic)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # 매일 00:00 UTC

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # requirements.txt가 있든 없든 필요한 것 바로 설치
          pip install "openai>=1.30.0" requests

      # 🔎 환경변수 존재 여부를 먼저 검사(값은 출력 안 함)
      - name: Sanity check env
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
        run: |
          check() { test -n "$2" && echo "$1: OK" || { echo "::error::$1 MISSING"; exit 1; }; }
          check OPENAI_API_KEY "${OPENAI_API_KEY}"
          check CLIENT_ID "${CLIENT_ID}"
          check CLIENT_SECRET "${CLIENT_SECRET}"
          check BLOGGER_REFRESH_TOKEN "${BLOGGER_REFRESH_TOKEN}"
          check BLOGGER_BLOG_ID "${BLOGGER_BLOG_ID}"

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
        run: |
          python main.py

      - name: Upload HTML artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-output
          path: output/*.html
