name: Auto Blogger

# 수동 실행 + (원하면) 예약 실행
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # 매일 00:00 UTC (한국 09:00)

# GitHub 토큰 권한 (필수)
permissions:
  contents: write

# 동시에 여러 번 돌지 않도록 (선택)
concurrency:
  group: auto-blogger
  cancel-in-progress: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # requirements.txt 없을 때 기본 패키지
            pip install google-api-python-client google-auth google-auth-oauthlib requests
          fi

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}               # (있으면 사용)
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
        run: |
          python main.py

      - name: Upload HTML artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-output
          path: output/*.html
